platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'ScaleForce' do
  pod 'Instabug'
  pod 'Crashlytics'

  pod 'Alamofire'
  pod 'KeychainAccess'
  pod 'Marshal'

  pod 'lottie-ios'
  pod 'MaterialComponents'

  pod 'BonMot'
  pod 'Anchorage'
  pod 'Swiftilities', :git => 'https://github.com/Raizlabs/Swiftilities', :branch => 'feature/heyltsjay/misc-enhancements'

  pod 'FrictionLess', :git => 'https://github.com/Raizlabs/FrictionLess', :branch =>  'feature/heyltsjay/materialTextField'

  pod 'GoogleAnalytics',   '~>3.0'

  target 'ScaleForceTests' do
    pod 'OHHTTPStubs/Swift'
  end

end

pod 'SwiftLint'
pod 'SwiftGen'
pod 'Sourcery'

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-ScaleForce/Pods-ScaleForce-acknowledgements.plist', 'ScaleForce/Resources/Acknowledgements.plist', :remove_destination => true)
end

